CREATE TABLE USUARIO(
	LOGIN VARCHAR2(50),
	PASS VARCHAR2(50),
	NUMEROIMAGENES NUMBER(5),
	CONSTRAINT PK_USUARIO PRIMARY KEY (LOGIN)
);



CREATE TABLE IMAGEN(
	TITULO VARCHAR2(50),
	FECHASUBIDA DATE,
	LIKES NUMBER(5),
	LOGIN VARCHAR2(50),
	CONSTRAINT PK_IMAGEN PRIMARY KEY (TITULO),
	CONSTRAINT FK_IMAGEN FOREIGN KEY (LOGIN) REFERENCES USUARIO(LOGIN)
	
);


INSERT INTO USUARIO VALUES ('Alberto', 'pass', '0');
INSERT INTO USUARIO VALUES ('Pepe', 'pass', '0');
INSERT INTO USUARIO VALUES ('Luis', 'pass', '0');
INSERT INTO USUARIO VALUES ('Paco', 'pass', '0');

INSERT INTO USUARIO VALUES ('Lute', 'pass', '-1');
INSERT INTO USUARIO VALUES ('Jose', 'pass', '-1');
INSERT INTO USUARIO VALUES ('Jiro', 'pass', '-1');
INSERT INTO USUARIO VALUES ('Andrea', 'pass', '-1');










